version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-ms
    image: inventory-ms:latest
#    command: ["bash", "/var/www/html/run.sh"]
    ports:
      - "8100:80"
    volumes:
      - ./:/var/www/html/backend/inventoryMs

